import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const payload={pickup:'Saket',drop:'Rohini',delivery_window_minutes:85,has_mask:false,max_aqi:300,aqi_standard:'US',travel_mode:'DRIVE'};
const points=[{lat:28.524,lng:77.213},{lat:28.62,lng:77.2},{lat:28.716,lng:77.117}];
const routes=[{id:'route-0',name:'AQI-weighted route',description:'OSRM driving option 1',coordinates:points,duration_seconds:2400,distance_meters:30000,average_aqi:120,max_sampled_aqi:130,exposure_index:4800,high_aqi_minutes:0,eligible:true,samples:[]},
  {id:'route-1',name:'Alternative route',description:'OSRM driving option 2',coordinates:[points[0],{lat:28.6,lng:77.09},points[2]],duration_seconds:2700,distance_meters:32000,average_aqi:110,max_sampled_aqi:125,exposure_index:4950,high_aqi_minutes:0,eligible:true,samples:[]}];
const fixture={trip_id:'fixture-ai-trip',origin:{name:'Saket'},destination:{name:'Rohini'},routes,standard_route_id:'route-0',green_route_id:'route-0',recommended_route_id:'route-0',lower_aqi_percent:0,exposure_reduction_percent:0,high_aqi_threshold:200,graph:{candidate_routes:2,samples:20,air_zones:3},warnings:['Fixture: regional model estimates.']};
try {
  await page.route('**/api/city-aqi',r=>r.fulfill({json:{aqi:120,observed_at:new Date().toISOString()}}));
  let parseBody,routeBody,analysisBody;
  await page.route('**/api/ai/parse-trip',async r=>{parseBody=r.request().postDataJSON();await r.fulfill({json:{status:'ready',payload,message:'Check the filled trip details, then show your ride. Limits use US AQI.'}})});
  await page.route('**/api/calculate-route',async r=>{routeBody=r.request().postDataJSON();await r.fulfill({json:fixture})});
  await page.route('**/api/ai/exposure-analysis',async r=>{analysisBody=r.request().postDataJSON();await r.fulfill({json:{source:'Gemini',story:{headline:'The direct route wins this comparison.',summary:'The quickest route also has the best eligible score. No exposure reduction was found against the fastest route.',tradeoff:'A longer alternative has cleaner average air, but its additional travel time increases the estimated exposure index.',caveat:'Regional model estimates can miss local changes. Driving times do not include live traffic.'}}})});
  await page.goto(process.env.FRONTEND_URL||'http://localhost:5173',{waitUntil:'networkidle'});
  assert.equal(await page.getByRole('button',{name:'Air quality',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'My impact',exact:true}).count(),0);
  await page.getByRole('textbox',{name:'Describe your trip'}).fill('Saket to Rohini in 85 minutes, AQI below 300, no mask.');
  await page.getByRole('button',{name:'Find my routes'}).click();
  await page.locator('.graph-proof').waitFor();
  assert.match(parseBody.prompt,/85 minutes/);
  assert.equal(await page.getByRole('combobox',{name:'PICKUP LOCATION'}).inputValue(),'Saket');
  assert.equal(await page.getByRole('combobox',{name:'DROP LOCATION'}).inputValue(),'Rohini');
  assert.equal(await page.getByRole('combobox',{name:'Delivery window'}).inputValue(),'85');
  assert.equal(await page.getByRole('spinbutton',{name:'Maximum sampled US AQI'}).inputValue(),'300');
  assert.equal(await page.getByRole('switch',{name:'I have a mask',exact:true}).getAttribute('aria-checked'),'false');
  await page.locator('.graph-proof').waitFor();
  assert.deepEqual(routeBody,payload);
  await page.getByRole('button',{name:'Explain this route'}).click();
  await page.locator('.analyst-story').waitFor();
  assert.deepEqual(analysisBody,{trip_id:'fixture-ai-trip',route_id:'route-0'});
  assert.match(await page.locator('.analyst-story').innerText(),/No exposure reduction/);
  await page.locator('.live-endpoint').first().waitFor({timeout:45000});
  await page.screenshot({path:'artifacts/gemini-desktop-fixture.png',fullPage:true});
  await page.getByRole('button',{name:/Alternative route.*OSRM driving option 2/}).click();
  assert.equal(await page.locator('.analyst-story').count(),0);
  await page.getByRole('button',{name:'Explain this route'}).click();
  await page.locator('.analyst-story').waitFor();
  assert.equal(analysisBody.route_id,'route-1');
  await page.getByRole('spinbutton',{name:'Maximum sampled US AQI'}).fill('100');
  await page.getByText('Your preferences changed. Show your ride again before requesting an explanation.').waitFor();
  assert.equal(await page.getByRole('button',{name:'Explain again'}).count(),0);
  await page.route('**/api/ai/parse-trip',r=>r.fulfill({json:{status:'needs_clarification',payload:null,message:'Please provide a pickup location.'}}));
  await page.getByRole('textbox',{name:'Describe your trip'}).fill('Take me to Rohini');
  await page.getByRole('button',{name:'Find my routes'}).click();
  await page.getByText('Please provide a pickup location.').waitFor();
  assert.equal(await page.getByRole('combobox',{name:'PICKUP LOCATION'}).inputValue(),'Saket');
  await page.route('**/api/ai/parse-trip',r=>r.fulfill({status:503,json:{detail:'Gemini is not connected yet. The manual planner still works.',code:'GEMINI_NOT_CONFIGURED'}}));
  await page.getByRole('button',{name:'Find my routes'}).click();
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').innerText(),/manual planner/);
  assert.equal(await page.getByRole('button',{name:'Show my ride',exact:true}).isEnabled(),true);
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=0.5);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'artifacts/gemini-mobile-fixture.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS (fixtures): Gemini intent fills exact route payload; custom deadline/mask/AQI limit; selected-route analysis; stale analysis hidden; clarification and missing-key recovery; removed navigation; mobile layout.');
} finally {await browser.close()}
