import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
const errors = [];
page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto('http://localhost:5173', {waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Demo data',exact:true}).click();
  await page.getByRole('heading',{name:'Your next ride, a little cleaner.'}).waitFor();
  await page.screenshot({path:'artifacts/rider-desktop.png',fullPage:true});
  assert.equal(await page.locator('.route-card').count(), 3);
  await page.getByRole('button',{name:/The quick way/}).click();
  assert.ok((await page.locator('.route-card.selected').innerText()).includes('The quick way'));
  await page.getByRole('switch',{name:'I have a mask',exact:true}).click();
  assert.ok(await page.locator('.constraint-note').isVisible());
  await page.getByRole('switch',{name:'Winter simulation'}).click();
  assert.equal(await page.locator('.constraint-note').count(),0);
  await page.getByRole('switch',{name:'Winter simulation'}).click();
  await page.getByRole('switch',{name:'I have a mask',exact:true}).click();

  await page.getByRole('combobox',{name:'PICKUP LOCATION'}).fill('Rohini');
  await page.getByRole('option',{name:/Rohini/}).click();
  await page.getByRole('button',{name:'Show my ride',exact:true}).click();
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').innerText(),/different/);
  await page.getByRole('combobox',{name:'PICKUP LOCATION'}).fill('Dwarka');
  await page.getByRole('option',{name:/Dwarka/}).click();
  await page.getByRole('button',{name:'Show my ride',exact:true}).click();
  await page.waitForTimeout(850);
  assert.match(await page.locator('.selected-summary').innerText(),/Dwarka/);
  await page.getByRole('button',{name:'Swap pickup and drop locations'}).click();
  assert.match(await page.getByRole('combobox',{name:'PICKUP LOCATION'}).inputValue(),/Rohini/);
  await page.getByRole('button',{name:'Show my ride',exact:true}).click();
  await page.waitForTimeout(850);
  await page.getByRole('button',{name:'Start demo ride',exact:true}).click();
  await page.getByRole('button',{name:'Start simulation',exact:true}).click();
  await page.getByRole('button',{name:'View ride',exact:true}).click();
  await page.getByRole('button',{name:'Complete demo ride',exact:true}).click();
  await page.getByRole('button',{name:/My rides/}).click();
  assert.equal(await page.locator('tbody tr').count(),4);
  await page.getByRole('textbox',{name:'Search rides'}).fill('unknown');
  await page.getByRole('heading',{name:'No journeys found'}).waitFor();
  await page.getByRole('button',{name:'Clear search'}).click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export CSV'}).click();
  const download=await downloadPromise;
  assert.equal(download.suggestedFilename(),'svas-aasrav-demo-rides.csv');

  await page.getByRole('button',{name:'Admin',exact:true}).click();
  await page.getByRole('heading',{name:'Better routes. A healthier fleet.'}).waitFor();
  await page.screenshot({path:'artifacts/admin-desktop.png',fullPage:true});
  assert.equal(await page.getByRole('button',{name:'Air quality',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Impact report',exact:true}).count(),0);
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('combobox',{name:'Default delivery window'}).selectOption('45');
  await page.getByRole('button',{name:'Reset defaults'}).click();
  assert.equal(await page.getByRole('combobox',{name:'Default delivery window'}).inputValue(),'75');
  await page.getByRole('button',{name:'Rider',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/rider-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.getByRole('button',{name:'Open navigation'}).click();
  assert.equal(await page.getByRole('button',{name:'My impact',exact:true}).count(),0);
  await page.getByRole('button',{name:/My rides/}).click();
  await page.getByRole('heading',{name:'Your road, so far.'}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.getByRole('button',{name:'Open navigation'}).click();
  await page.getByRole('button',{name:'Admin',exact:true}).click();
  await page.getByRole('heading',{name:'Better routes. A healthier fleet.'}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:'artifacts/admin-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS: desktop/mobile layout, location search, validation, constraints, route selection, ride completion, history search/export, Admin, removed Air quality/Impact navigation and settings. No browser runtime errors.');
} finally { await browser.close(); }
