import { useEffect, useRef, useState } from 'react';
import { ArrowDownUp, ArrowRight, ArrowUpRight, Bike, Check, CircleHelp, Clock3, Database, Leaf, MapPin, Navigation, RefreshCw, ShieldCheck, TrendingDown, Wind } from 'lucide-react';
import LiveRouteMap from './LiveRouteMap';
import RoutePollutionProfile from './RoutePollutionProfile';
import { NaturalLanguagePlanner, ExposureAnalyst } from './GeminiAssistant';
import { calculateRoute,getCityAqi,getGraphSummary,usAqiLabel } from './api';
import { locations } from './data';

const requestSignature = value => JSON.stringify(Object.keys(value).sort().map(key=>[key,value[key]]));

function Metric({icon:Icon,label,value,unit,note,tone='green'}) { return <div className="stat-card"><span className={`stat-icon ${tone}`}><Icon size={20}/></span><div className="stat-content"><span className="stat-label">{label}</span><div className="stat-value">{value}<span>{unit}</span></div><span className="stat-note">{note}</span></div></div>; }

export function LiveGraphPanel() {
  const [data,setData]=useState(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();setError('');getGraphSummary(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[attempt]);
  return <section className="live-graph-panel"><div className="section-heading"><div><h2><Database size={17}/>Shared air-quality areas</h2><p>Recent route comparisons</p></div><button className="outline-button" onClick={()=>setAttempt(n=>n+1)}><RefreshCw size={13}/>Refresh</button></div>{error?<p className="connection-message">{error}</p>:!data?<p className="muted">Loading comparisons…</p>:!data.zones.length?<p className="connection-message">Calculate a ride to compare air-quality areas.</p>:<div className="graph-zone-list">{data.zones.map(z=><div key={z.id}><MapPin size={17}/><span><strong>{z.station_name||`Grid ${z.lat.toFixed(2)}, ${z.lng.toFixed(2)}`}</strong><small>{z.affected_routes} candidate routes share this air-quality area</small></span><b>{Math.round(z.aqi)}<small>US AQI</small></b></div>)}</div>}</section>;
}

export default function LivePlanner() {
  const [pickup,setPickup]=useState('Saket, New Delhi'),[drop,setDrop]=useState('Rohini, New Delhi');
  const [windowMinutes,setWindowMinutes]=useState(75),[mask,setMask]=useState(true),[travelMode]=useState('DRIVE');
  const [maxAqi,setMaxAqi]=useState('');
  const [city,setCity]=useState(null),[cityError,setCityError]=useState(''),[cityAttempt,setCityAttempt]=useState(0);
  const [result,setResult]=useState(null),[submitted,setSubmitted]=useState(''),[selected,setSelected]=useState('');
  const [loading,setLoading]=useState(false),[error,setError]=useState('');
  const requestRef=useRef(null);
  const payload={pickup:pickup.trim(),drop:drop.trim(),delivery_window_minutes:windowMinutes,has_mask:mask,travel_mode:travelMode,max_aqi:maxAqi===''?null:Number(maxAqi),aqi_standard:'US'};
  const dirty=!!result&&requestSignature(payload)!==submitted;
  useEffect(()=>{const controller=new AbortController();setCityError('');getCityAqi(controller.signal).then(setCity).catch(e=>{if(e.name!=='AbortError')setCityError(e.message)});return()=>controller.abort()},[cityAttempt]);
  useEffect(()=>()=>requestRef.current?.abort(),[]);
  const edit=(setter,value)=>{requestRef.current?.abort();setLoading(false);setError('');setter(value)};
  function applyIntent(next){requestRef.current?.abort();setLoading(false);setError('');setResult(null);setPickup(next.pickup);setDrop(next.drop);setWindowMinutes(next.delivery_window_minutes);setMask(next.has_mask);setMaxAqi(next.max_aqi??'');return submit(null,next)}
  async function submit(event,requestPayload=payload){
    event?.preventDefault();requestRef.current?.abort();setError('');
    if(requestPayload.pickup.length<2||requestPayload.drop.length<2){setError('Enter both pickup and drop locations.');return}
    if(requestPayload.pickup.toLowerCase()===requestPayload.drop.toLowerCase()){setError('Choose different pickup and drop locations.');return}
    const controller=new AbortController();requestRef.current=controller;setLoading(true);
    // Clear stale results on failure; never retain mock or unrelated route metrics.
    setResult(null);
    try{const next=await calculateRoute(requestPayload,controller.signal);setResult(next);setSubmitted(requestSignature(requestPayload));setSelected(next.recommended_route_id||next.green_route_id)}
    catch(e){if(e.name!=='AbortError')setError(e.message)}
    finally{if(requestRef.current===controller)setLoading(false)}
  }
  const current=result?.routes.find(r=>r.id===selected);
  const exposure=result?.exposure_reduction_percent;
  const lowerAqi=result?.lower_aqi_percent;
  const stationMode=(result?.aqi_source||city?.source||'').startsWith('WAQI');
  const credits=result?.attributions||city?.attributions||[];
  const sameRoute=result&&result.standard_route_id===result.green_route_id;
  return <>
    <div className="page-heading"><div><div className="eyebrow greeting">A LITTLE CARE GOES A LONG WAY <span>✳</span></div><h1>Your next ride, a little cleaner<span>.</span></h1><p>Find the lowest-exposure route that meets your time and air-quality requirements.</p></div><span className="connection-badge"><Database size={13}/>Connected planner</span></div>
    <div className="scenario-banner live-banner"><span className="scenario-icon"><Wind size={19}/></span><div><strong>Real routes. Honest estimates.</strong><p>{stationMode?'Comparing nearby monitoring stations along each route. A cleaner route is never guaranteed.':'Regional model data can be identical across nearby routes. A reduction is never guaranteed.'}</p></div><span className="tiny-badge">US AQI | {stationMode?'STATIONS':'REGIONAL'}</span></div>
    <div className="stats-grid"><Metric icon={Wind} label="Delhi air quality" value={cityError?'—':city?Math.round(city.aqi):'…'} unit="US AQI" note={cityError?'Air-quality service unavailable':city?`${usAqiLabel(city.aqi)} · ${new Date(city.observed_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'Fetching current model estimate…'} tone="peach"/><Metric icon={TrendingDown} label="Estimated exposure change" value={exposure==null?'—':`${Math.abs(exposure)}%`} unit={exposure==null?'plan a ride':exposure>=0?'lower index':'higher index'} note={result?'AQI × estimated minutes · graph comparison':'Calculated after comparing actual routes'}/><Metric icon={ShieldCheck} label="Route-average AQI change" value={lowerAqi==null?'—':`${Math.abs(lowerAqi)}%`} unit={lowerAqi==null?'plan a ride':lowerAqi>=0?'lower AQI':'higher AQI'} note={result?(result.recommended_route_id?'Recommended vs. fastest driving route':'Best available vs. fastest; none qualify'):'No hardcoded pollution reduction'} tone="lavender"/></div>
    {cityError&&<div className="api-alert" role="status"><CircleHelp size={17}/><span>{cityError}</span><button onClick={()=>setCityAttempt(n=>n+1)}><RefreshCw size={13}/>Retry AQI</button></div>}
    <NaturalLanguagePlanner formVersion={JSON.stringify(payload)} defaults={{delivery_window_minutes:windowMinutes,has_mask:mask,max_aqi:payload.max_aqi}} onApply={applyIntent}/>
    <div className="ride-layout live-ride-layout"><section className="planner-panel"><div className="section-heading"><h2>Where are we headed?</h2><span className="soft-icon"><Navigation size={17}/></span></div>
      <form onSubmit={submit}><div className="location-fields"><div className="location-field"><span className="location-dot"/><div><label htmlFor="live-pickup">PICKUP LOCATION</label><input id="live-pickup" name="pickup" value={pickup} onChange={e=>edit(setPickup,e.target.value)} list="delhi-locations" placeholder="e.g. Saket, New Delhi" autoComplete="off" required maxLength={250}/></div></div><div className="location-connector"/><button type="button" className="swap-button" aria-label="Swap pickup and drop locations" onClick={()=>{edit(setPickup,drop);setDrop(pickup)}}><ArrowDownUp size={15}/></button><div className="location-field"><span className="location-dot destination"/><div><label htmlFor="live-drop">DROP LOCATION</label><input id="live-drop" name="drop" value={drop} onChange={e=>edit(setDrop,e.target.value)} list="delhi-locations" placeholder="e.g. Rohini, New Delhi" autoComplete="off" required maxLength={250}/></div></div></div><datalist id="delhi-locations">{locations.map(l=><option key={l.id} value={`${l.name}, ${l.detail}`}/>)}</datalist>
      <div className="ride-preferences"><label><Clock3 size={14}/><span>Deliver within</span><select aria-label="Delivery window" value={windowMinutes} onChange={e=>edit(setWindowMinutes,Number(e.target.value))}>{![20,30,45,60,75,90,120].includes(windowMinutes)&&<option value={windowMinutes}>{windowMinutes} min</option>}<option value={20}>20 min</option><option value={30}>30 min</option><option value={45}>45 min</option><option value={60}>60 min</option><option value={75}>75 min</option><option value={90}>90 min</option><option value={120}>2 hours</option></select></label><label><Bike size={14}/><span>Route profile</span><span className="profile-value">Driving / no live traffic</span></label><label className="aqi-limit-field"><Wind size={14}/><span>Sample AQI below</span><input aria-label="Maximum sampled US AQI" type="number" min="1" max="501" step="1" placeholder="No limit" value={maxAqi} onChange={e=>edit(setMaxAqi,e.target.value)}/><small>US</small></label><div><ShieldCheck size={14}/><span>I have a mask</span><button type="button" className={`toggle ${mask?'on':''}`} role="switch" aria-label="I have a mask" aria-checked={mask} onClick={()=>edit(setMask,!mask)}><span/></button></div></div>
      {error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button show-ride" type="submit" disabled={loading}>{loading?<><span className="spinner"/>Comparing routes…</>:<><Navigation size={16}/>Show my ride<ArrowRight size={17}/></>}</button></form>
      <div className="route-list-heading"><h3>Your route options <span>{result?.routes.length||0}</span></h3><span className="tiny-badge">{result?'EXPOSURE RANKED':'LIVE'}</span></div>
      {dirty&&<p className="pending-note">Your preferences changed. Show your ride again to update the comparison.</p>}
      {result?.deadline_summary&&!result.deadline_summary.any_route_on_time&&<div className="deadline-alert" role="alert"><Clock3 size={19}/><div><strong>{result.deadline_summary.requested_minutes}-minute deadline cannot be met</strong><p>Fastest available: {result.deadline_summary.fastest_minutes} min ? {result.deadline_summary.minimum_extra_minutes} min late. No route is recommended. Estimates exclude live traffic.</p></div></div>}
      {result&&!result.recommended_route_id&&<p className="constraint-note">No route meets all your delivery, mask and AQI preferences. Review your constraints.</p>}
      {!result&&<div className="route-empty"><Navigation size={29}/><h3>A better route starts here.</h3><p>{loading?'Comparing road options, journey times and air quality…':'Enter any Delhi NCR address. We’ll compare available road routes.'}</p></div>}
      <div className="route-options">{result?.routes.map(route=><button key={route.id} className={`route-card ${selected===route.id?'selected':''}`} aria-pressed={selected===route.id} onClick={()=>setSelected(route.id)}><div className="route-card-top"><span className={`route-radio ${selected===route.id?'checked':''}`}/><strong>{route.id===result.recommended_route_id?'Lowest-exposure route':route.id===result.standard_route_id?'The quick way':`Alternative route ${result.routes.indexOf(route)}`}</strong><span className={`route-tag ${route.id===result.recommended_route_id?'recommended':''}`}>{route.id===result.recommended_route_id?'RECOMMENDED':route.id===result.standard_route_id?'FASTEST':'ALTERNATIVE'}</span></div><p className="route-via">{route.description}</p><div className="route-metrics"><span><Clock3 size={13}/><b>{Math.ceil(route.duration_seconds/60)}</b> min</span><i/><span>{(route.distance_meters/1000).toFixed(1)} km</span><span className={`aqi-pill ${route.average_aqi>200?'bad':'medium'}`}><Wind size={12}/>{Number(route.average_aqi).toFixed(1)} US</span></div>{route.late_by_minutes>0&&<div className="route-late"><Clock3 size={13}/>{route.late_by_minutes} min late</div>}{route.constraint_failures?.filter(reason=>!reason.includes('deadline')).map(reason=><div className="route-failure" key={reason}>{reason}</div>)}{selected===route.id&&<div className="route-note"><ShieldCheck size={13}/>{route.high_aqi_minutes} min above US AQI {result.high_aqi_threshold}</div>}</button>)}</div>
      <div className="simulation-footnote"><span/>{result?'AQI estimates / not personal exposure measurements':'No simulated data in Live mode'}</div>
    </section><div className="map-column"><LiveRouteMap routes={result?.routes} standardRouteId={result?.standard_route_id} greenRouteId={result?.green_route_id} noRecommendation={!!result&&!result.recommended_route_id} stationMode={stationMode} selectedRouteId={selected} onSelect={setSelected}/>{current&&<div className="selected-summary live-selected-summary"><span className="summary-icon"><Bike size={24}/></span><div><span>YOUR SELECTED ROUTE</span><strong>{result.origin.formatted_address||result.origin.name}<ArrowRight size={14}/>{result.destination.formatted_address||result.destination.name}</strong></div><div className="summary-duration"><strong>{Math.ceil(current.duration_seconds/60)}<small> min</small></strong><span>{(current.distance_meters/1000).toFixed(1)} km · {current.late_by_minutes>0?`${current.late_by_minutes} min late`:current.eligible?'Within preferences':'Does not meet preferences'}</span></div></div>}</div></div>
    {result&&<RoutePollutionProfile result={result} selectedRouteId={selected} onSelect={setSelected}/>}
    {result&&<ExposureAnalyst key={`${result.trip_id}:${selected}`} result={result} selectedRouteId={selected} dirty={dirty}/>}
    {result&&<><section className="graph-proof"><span className="stat-icon green"><Database size={22}/></span><div><span className="eyebrow">HOW YOUR OPTIONS COMPARE</span><h3>{result.graph.candidate_routes} routes. {result.graph.samples} samples. {result.graph.air_zones} {stationMode?'stations':'air-quality areas'}.</h3><p>Trip → candidate routes → samples → air-quality readings</p></div><span className="tiny-badge">{!result.recommended_route_id?'NO QUALIFYING ROUTE':sameRoute?'SAME ROUTE WINS':'EXPOSURE FIRST'}</span></section><div className="route-disclosures"><h3><CircleHelp size={16}/>About this comparison</h3>{result.warnings.map((message,i)=><p key={i}>{message}</p>)}</div></>}
    <div className="data-note"><Leaf size={18}/><p>Air-quality data: {stationMode?<><a href="https://waqi.info/" target="_blank" rel="noreferrer">World Air Quality Index Project</a>{credits.filter(a=>!a.name.includes('World Air Quality')).map(a=><span key={a.url}> / <a href={a.url} target="_blank" rel="noreferrer">{a.name}</a></span>)}. Nearby station readings estimate conditions along the road. </>:<> <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> / <a href="https://atmosphere.copernicus.eu/" target="_blank" rel="noreferrer">CAMS</a>. US AQI, not Indian AQI. Regional estimates are not street-level sensor measurements. </>} US AQI is not Indian AQI. Map data: &copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a> contributors. <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noreferrer">Fix the map</a>. No live traffic or motorcycle routing.</p></div>
  </>;
}
